<a href="https://colab.research.google.com/github/ibe-abu-chi/python_EDA/blob/master/CKD_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [164]:
#importing all libraries and data needed for this exercise
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt
CKData = pd.read_excel('CKD_DATA.xlsx')
#pd.set_option('max_columns', None)
#pd.set_option('max_rows', None)

In [166]:
#viewing the head of the data set
CKData

,YEAR,CATEGORY_CODE,AGE,GENDER,RACE,AGE AT BIOPSY,ONSET TO BIOPSY TIME,M,E,S,T,C,IgAstain,IgGstain,IgMstain,C3STAIN,WEIGHT,HEIGHT,BMI,P_PROTEINURIA,P_HEMATURIA,P_HTN,P_EDEMA,P_AKI,P_ESRD,P_NS,C3,C4,C3C4R,URIC ACID,B_PROTEIN,B_ALBUMIN,B_CHOLESTEROL,B_HEMATOCRIT,B_PLATELET,WBC,NEUTRO,LYMPHO,NLR,B_SBP,B_DBP,B_PP,B_MAP,24HRUPROTEIN,HEMATURIA,B_creatinine,B_eGFR,B_UPCR,B_ACE,B_STEROID,B_CYTOTOXICS,B_AZATHIOPRINE,Unnamed: 52,6_SBP,6_DBP,6_PP,6_MAP,6_PROTEINURIA,6_HEMATURIA,6_CREATININE,6_Egfr,6_UPCR,6_ACE,6_STEROID,6_IMMNU,6_AZATHIO,Unnamed: 66,1_SBP,1_DBP,1_PP,1_MAP,1_PROTEINURIA,HEMATURIA.1,1_creatinine,1_eGFR,1_UPCR,1_ACE,1_STEROID,1_CYTO,1_AZATHIOPRINE,Unnamed: 80,5_SBP,5_DBP,5_PROTEINURIA,5_HEMATURIA,5_CREATININE,5_eGFR,5_UPCR,Unnamed: 88,L_DATE,L_ACE,L_STEROID,L_CYTO,L_AZATHIOPRINE,L_SBP,L_DBP,L_PP,L_MAP,L_MAP.1,L_CRETININE,L_eGFR,L_HEMATURIA,L_PROTEINURIA,L_UPCR,Unnamed: 104,OUTCOME,FUT,Unnamed: 107
0,2012,12305,40,FEMALE,MELAYU,30,30,1,0.0,1,1,0.0,2+,1+,TRACE,NEG,73.0,1.53,31.180000,1,0,1,0,0,0,0,NaN,NaN,NaN,NaN,71.0,35,3.78,12.5,311,11.90,6.33,2.87,2.200000,139.0,96.0,43.0,110.0,1.400,NEG,121,53,0.11,1,0,0,0,NaN,115.0,72.0,43.0,86.000000,2+,NEG,119.0,54.0,0.26,NaN,0.0,0.0,0.0,NaN,151.0,109.0,42.0,123.0,2+,TRACE,119.0,54.0,0.26,1.0,0,0,0,NaN,109.0,65,NaN,2+,209,27,0.15,NaN,2022,1,0,0,0,113,72,41.0,86.0,110.0,803,5,-,-,0.67,NaN,ESRD,120,NaN
1,2012,4292,38,FEMALE,MELAYU,28,36,1,0.0,1,1,0.0,3+,TRACE,2+,2+,57.0,-,NaN,1,1,1,0,0,0,0,NaN,NaN,NaN,362.0,68.0,33,NaN,11.7,413,10.70,7.74,1.91,4.100000,120.0,81.0,39.0,94.0,1.340,2+,82,86,0.40,0,0,0,0,NaN,129.0,80.0,49.0,96.000000,TRACE,TRACE,123.0,53.0,0.04,1.0,0.0,0.0,0.0,NaN,142.0,100.0,42.0,114.0,2+,1+,92.0,75.0,0.16,1.0,0,0,0,NaN,179.0,122,NaN,3+,258,21,0.18,NaN,2022,1,0,0,0,140,90,50.0,107.0,137.0,417,11,TRACE,1+,0.08,NaN,50PERC,60,NaN
2,2012,3213,38,FEMALE,MELAYU,27,9,1,NaN,1,1,1.0,2+,NEG,1+,NEG,52.0,-,NaN,1,0,1,0,0,0,0,NaN,NaN,NaN,292.0,63.0,35,NaN,12.1,433,13.10,10.90,1.40,7.800000,149.0,103.0,46.0,118.0,2.600,NEG,74,98,0.26,1,1,0,0,NaN,145.0,103.0,42.0,117.000000,NEG,NEG,73.0,100.0,0.22,1.0,1.0,0.0,1.0,NaN,129.0,84.0,45.0,99.0,TRACE,TRACE,64.0,116.0,0.12,1.0,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,1,1,0,0,142,99,43.0,113.0,146.0,59,120,1+,0,0.09,NaN,NO,48,NaN
3,2012,10911,41,FEMALE,MELAYU,31,10,0,1.0,1,0,1.0,1+,1+,1+,NEG,80.0,NaN,NaN,1,0,0,1,0,0,0,2.16,0.72,3.00,NaN,73.0,39,6.97,13.3,365,15.90,11.90,3.09,3.900000,132.0,78.0,54.0,96.0,10.940,NEG,59,120,0.14,0,1,0,0,NaN,121.0,83.0,38.0,96.000000,2+,NEG,74.0,96.0,0.02,1.0,1.0,0.0,0.0,NaN,148.0,97.0,51.0,114.0,NEG,2+,76.0,92.0,0.02,1.0,0,0,0,NaN,101.0,70,NaN,NEG,65,108,0.02,NaN,2022,1,0,0,0,138,85,53.0,103.0,131.0,70,96,1+,TRACE,0.02,NaN,NO,120,NaN
4,2012,7084,34,MALE,MELAYU,24,5,0,1.0,1,0,1.0,3+,NEG,2+,1+,98.0,1.69,34.310000,0,0,0,1,0,0,1,NaN,NaN,NaN,NaN,50.0,20,8.65,13.2,310,7.30,3.97,2.52,1.600000,135.0,82.0,53.0,100.0,9.200,NEG,76,124,0.63,0,0,1,0,NaN,124.0,67.0,57.0,86.000000,NEG,NEG,75.0,125.0,NaN,1.0,1.0,0.0,0.0,NaN,126.0,80.0,46.0,95.0,3+,TRACE,76.0,96.0,0.19,0.0,1,1,0,NaN,118.0,68,NaN,NEG,75,121,0.01,NaN,2022,0,1,1,0,120,81,39.0,94.0,121.0,91,98,TRACE,4+,0.31,NaN,NO,120,NaN
5,2012,12092,29,MALE,MELAYU,19,1,1,1.0,1,2,2.0,2+,TRACE,1+,1+,57.5,1.62,21.910000,0,0,0,0,0,0,0,1.19,0.35,3.40,NaN,57.0,28,7.19,10.0,404,8.80,4.48,1.34,3.300000,145.0,84.0,61.0,104.0,2.855,2+,370,20,0.67,0,0,0,0,NaN,175.0,111.0,64.0,132.000000,NaN,NaN,434.0,16.0,0.40,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,731.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,7,DELETE L
6,2012,12954,32,FEMALE,MELAYU,22,1,0,0.0,1,0,0.0,3+,1+,2+,1+,69.0,1.52,29.860000,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,76.0,36,4.67,12.3,302,8.90,5.49,2.75,2.000000,131.0,68.0,63.0,89.0,6.500,2+,61,126,0.17,0,0,0,0,NaN,125.0,81.0,44.0,96.000000,1+,2+,70.0,108.0,NaN,1.0,0.0,0.0,0.0,NaN,118.0,56.0,62.0,77.0,2+,3+,58.0,127.0,NaN,1.0,0,0,0,NaN,115.0,78,NaN,1+,71,103,0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,60,DELETE L
7,2012,12786,51,FEMALE,OTHERS,41,1,0,NaN,1,1,1.0,3+,TRACE,1+,1+,49.8,1.41,25.050000,0,0,1,1,0,0,0,1.34,0.46,2.91,NaN,63.0,31,NaN,10.8,155,13.20,8.48,2.98,2.800000,134.0,84.0,50.0,101.0,4.300,3+,331,15,0.71,0,0,0,0,NaN,180.0,118.0,62.0,139.000000,2+,1+,347.0,14.0,NaN,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,124,62,62.0,83.0,103.0,568,7,NaN,NaN,NaN,NaN,ESRD,6,DELETE L
8,2013,12712,34,FEMALE,OTHERS,25,6,1,0.0,1,0,1.0,3+,2+,1+,2+,79.0,1.55,32.880000,1,0,0,0,0,0,0,1.92,0.49,3.92,557.0,65.0,29,7.72,11.6,122,8.30,5.15,2.40,2.100000,147.0,96.0,51.0,113.0,4.900,2+,91,77,0.30,1,0,0,0,NaN,130.0,84.0,46.0,99.000000,2+,2+,127.0,52.0,0.25,1.0,1.0,0.0,0.0,NaN,130.0,84.0,46.0,99.0,2+,2+,112.0,60.0,0.23,1.0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NO,12,DELETE L
9,2013,11846,43,MALE,MELAYU,34,60,1,0.0,1,0,1.0,2+,1+,1+,NaN,64.0,NaN,NaN,0,0,1,0,0,0,0,1.11,0.33,3.36,NaN,68.0,33,4.58,12.6,287,18.10,13.90,2.65,5.200000,133.0,84.0,49.0,100.0,NaN,1+,161,49,0.22,1,0,0,0,NaN,140.0,83.0,57.0,102.000000,4+,NEG,171.0,46.0,NaN,1.0,0.0,0.0,0.0,NaN,181.0,134.0,47.0,150.0,4+,NEG,206.0,36.0,NaN,1.0,0,0,0,NaN,157.0,100,NaN,NEG,324,21,0.26,NaN,2022,NaN,NaN,NaN,NaN,169,76,93.0,107.0,132.0,1119,3,NaN,NaN,NaN,NaN,50PERC,60,DELETE L
10,2013,355,65,MALE,OTHERS,55,96,0,0.0,1,2,NaN,3+,TRACE,2+,2+,64.0,1.69,22.410000,1,1,1,0,0,0,0,NaN,NaN,NaN,674.0,68.0,34,NaN,11.5,196,9.20,6.08,2.02,3.000000,129.0,91.0,38.0,104.0,NaN,1+,293,21,0.29,1,0,0,0,NaN,133.0,81.0,52.0,98.000000,2+,1+,389.0,15.0,NaN,1.0,0.0,0.0,0.0,NaN,151.0,91.0,60.0,111.0,2+,1+,610.0,9.0,NaN,1.0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,12,NaN
11,2013,3921,32,FEMALE,MELAYU,23,36,1,0.0,2,1,1.0,3+,TRACE,TRACE,1+,54.0,1.56,22.190000,1,1,0,0,0,0,0,NaN,NaN,NaN,NaN,65.0,31,4.95,11.6,268,7.70,4.19,2.93,1.400000,140.0,85.0,55.0,103.0,1.400,3+,97,73,0.47,1,0,0,0,NaN,141.0,79.0,62.0,100.000000,2+,1+,84.0,86.0,NaN,1.0,1.0,0.0,0.0,NaN,178.0,96.0,82.0,123.0,2+,1+,84.0,86.0,NaN,1.0,1,0,0,NaN,146.0,81,NaN,1+,173,35,0.08,NaN,5/20/2021,1,1,0,0,132,86,46.0,101.0,130.0,192,30,NEG,1+,0.02,NaN,50PERC,60,DELETE L
12,2013,1909,36,FEMALE,MELAYU,27,2,1,0.0,1,0,1.0,2+,NEG,TRACE,TRACE,48.0,1.44,23.150000,1,0,0,0,0,0,0,NaN,NaN,NaN,417.0,73.0,34,4.62,12.0,258,6.90,5.14,2.75,1.900000,120.0,74.0,46.0,89.0,1.480,2+,64,117,0.23,1,0,0,0,NaN,128.0,88.0,40.0,101.000000,3+,2+,72.0,101.0,0.59,0.0,1.0,0.0,0.0,NaN,134.0,74.0,60.0,94.0,TRACE,TRACE,74.0,97.0,0.13,1.0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42251,1,1,0,0,117,69,48.0,85.0,108.0,76,94,NaN,2+,0.1,NaN,NO,24,NaN
13,2014,7892,31,MALE,MELAYU,22,4,1,0.0,1,2,1.0,3+,NEG,NEG,2+,60.0,1.3,35.500000,1,1,1,0,0,0,0,1.19,0.44,2.70,670.0,69.0,42,5.06,13.8,252,7.00,4.58,2.47,1.900000,128.0,83.0,45.0,98.0,NaN,2+,216,37,0.26,1,0,0,0,NaN,149.0,89.0,60.0,109.000000,4+,1+,289.0,26.0,NaN,1.0,0.0,0.0,0.0,NaN,150.0,69.0,81.0,96.0,2+,1+,418.0,17.0,0.34,1.0,0,0,0,NaN,150.0,93,NaN,NaN,1573,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,12,NaN
14,2014,12611,45,MALE,MELAYU,37,23,1,0.0,1,2,0.0,3+,NEG,1+,2+,62.0,1.57,25.150000,0,0,1,0,0,0,0,1.22,0.43,2.84,914.0,67.0,32,NaN,10.6,238,5.20,2.81,2.04,1.400000,123.0,79.0,44.0,94.0,NaN,1+,347,19,0.61,1,0,0,0,NaN,143.0,89.0,54.0,107.000000,2+,NEG,537.0,11.0,0.15,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,3+,NEG,427.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,6,NaN
15,2014,4520,52,FEMALE,MELAYU,44,22,1,1.0,1,1,1.0,3+,TRACE,2+,1+,53.0,NaN,NaN,1,1,1,0,0,0,0,1.31,0.42,3.12,NaN,72.0,31,NaN,11.4,199,6.70,3.87,2.04,1.900000,127.0,68.0,59.0,88.0,NaN,2+,295,17,0.31,1,0,0,0,NaN,119.0,70.0,49.0,86.000000,3+,NEG,501.0,9.0,0.45,0.0,0.0,0.0,0.0,NaN,134.0,92.0,42.0,106.0,NaN,NaN,680.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,6,NaN
16,2014,2258,27,MALE,MELAYU,20,15,1,0.0,1,2,1.0,3+,NEG,1+,1+,62.0,1.66,22.500000,1,1,0,0,0,0,0,NaN,NaN,NaN,490.0,57.0,24,9.23,13.7,293,7.40,4.07,2.23,1.800000,129.0,81.0,48.0,97.0,7.560,3+,142,63,0.57,1,0,0,0,NaN,151.0,81.0,70.0,104.000000,2+,2+,146.0,61.0,0.42,1.0,1.0,0.0,0.0,NaN,159.0,93.0,66.0,115.0,4+,3+,216.0,38.0,0.63,1.0,0,0,NaN,NaN,111.0,78,NaN,NaN,1307,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,485,14,NaN,NaN,NaN,NaN,ESRD,60,NaN
17,2014,8575,39,FEMALE,MELAYU,31,1,1,0.0,1,0,0.0,3+,1+,1+,TRACE,62.8,1.5,27.910000,1,0,0,1,0,0,1,1.22,0.37,3.30,279.0,59.0,23,10.34,12.1,301,7.50,4.89,3.29,1.500000,102.0,73.0,29.0,83.0,1.610,3+,56,121,0.56,0,1,0,0,NaN,116.0,65.0,51.0,82.000000,3+,3+,53.0,132.0,NaN,1.0,0.0,0.0,0.0,NaN,116.0,65.0,51.0,82.0,NEG,TRACE,52.0,123.0,0.09,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/23/2021,0,1,0,NaN,143,69,74.0,94.0,117.0,66,105,TRACE,NEG,NaN,NaN,NO,84,NaN
18,2014,5083,55,FEMALE,MELAYU,47,6,1,0.0,1,0,0.0,3+,TRACE,TRACE,NEG,47.8,1.53,20.420000,1,0,1,1,0,1,0,1.51,0.79,1.91,NaN,43.0,10,13.39,13.5,452,6.50,4.65,2.00,2.300000,106.0,74.0,32.0,85.0,1.300,1+,50,113,0.91,1,0,0,0,NaN,138.0,78.0,60.0,98.000000,NEG,3+,59.0,109.0,0.00,1.0,1.0,0.0,0.0,NaN,137.0,83.0,54.0,101.0,NEG,NEG,53.0,111.0,0.00,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42495,0,0,0,NaN,128,76,52.0,93.0,119.0,57,108,NEG,NEG,NaN,NaN,NO,24,NaN
19,2014,10333,38,FEMALE,INDIAN,30,1,1,0.0,1,2,1.0,3+,NEG,NEG,2+,84.0,1.66,30.480000,1,1,1,0,0,0,0,1.44,0.39,3.69,325.0,65.0,23,5.81,10.4,248,7.00,4.67,1.50,3.100000,128.0,95.0,33.0,106.0,NaN,5+,319,17,0.32,1,0,0,0,NaN,202.0,124.0,78.0,150.000000,NEG,1+,217.0,26.0,0.07,1.0,1.0,0.0,0.0,NaN,153.0,96.0,57.0,115.0,2+,TRACE,213.0,27.0,0.11,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,12,NaN
20,2014,12429,36,MALE,MELAYU,29,24,1,0.0,1,1,0.0,3+,TRACE,NEG,2+,64.5,1.58,25.840000,1,1,1,0,0,0,0,1.24,0.21,5.90,713.0,71.0,31,7.74,14.4,269,10.90,7.02,2.56,2.700000,121.0,57.0,64.0,78.0,NaN,TRACE,253,30,0.31,0,0,0,0,NaN,112.0,55.0,57.0,74.000000,TRACE,TRACE,293.0,19.0,NaN,1.0,0.0,0.0,0.0,NaN,130.0,66.0,64.0,87.0,TRACE,NEG,293.0,25.0,0.11,1.0,0,0,NaN,NaN,147.0,98,NaN,NEG,761,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESRD,60,NaN
21,2014,12235,49,MALE,MELAYU,41,-,1,0.0,1,0,0.0,2+,2+,1+,2+,78.2,1.56,32.130000,1,1,0,1,1,0,0,1.42,0.46,3.09,NaN,48.0,12,3.73,11.9,111,11.80,5.06,1.18,4.300000,139.0,86.0,53.0,104.0,1.240,5+,348,19,0.86,0,0,0,0,NaN,162.0,103.0,59.0,123.000000,4+,2+,94.0,67.0,1.61,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,6,NaN
22,2015,1955,41,FEMALE,MELAYU,33,11,1,0.0,1,0,0.0,3+,NEG,1+,1+,88.2,1.57,35.780000,1,1,0,1,0,0,0,1.14,0.51,2.24,358.0,64.0,28,NaN,10.2,317,9.00,8.02,2.19,3.700000,102.0,73.0,29.0,83.0,1.080,3+,80,86,0.10,1,0,0,0,NaN,120.0,79.0,41.0,93.000000,2+,2+,72.0,98.0,0.10,1.0,0.0,0.0,0.0,NaN,148.0,93.0,55.0,111.0,4+,2+,79.0,87.0,0.10,1.0,0,0,NaN,NaN,130.0,79,NaN,NEG,91,71,0.09,NaN,5/19/2022,1,0,0,NaN,111,75,36.0,87.0,112.0,106,59,1+,NEG,0.05,NaN,NO,84,NaN
23,2015,4484,37,FEMALE,MELAYU,29,26,1,0.0,1,1,0.0,1+,NEG,1+,1+,63.0,1.47,29.150000,1,0,1,0,0,0,0,NaN,NaN,NaN,347.0,68.0,33,6.10,12.0,300,13.20,5.79,2.03,2.900000,203.0,116.0,87.0,145.0,2.600,2+,109,61,0.28,1,0,0,0,NaN,195.0,133.0,62.0,154.000000,3+,3+,73.0,98.0,0.27,1.0,0.0,0.0,0.0,NaN,200.0,127.0,73.0,151.0,3+,NEG,88.0,78.0,0.14,1.0,0,0,NaN,NaN,197.0,103,NaN,TRACE,131,47,0.32,NaN,44384,1,1,0,0,115,69,46.0,84.0,107.0,195,29,3+,NEG,0.01,NaN,NO,72,NaN
24,2015,3377,70,FEMALE,INDIAN,63,4,1,1.0,1,0,2.0,2+,NEG,TRACE,1+,72.0,1.61,27.780000,1,1,1,0,0,0,0,NaN,NaN,NaN,335.0,60.0,25,5.64,10.7,407,9.80,5.64,3.52,1.600000,176.0,76.0,100.0,109.0,1.800,3+,110,47,0.91,1,0,0,0,NaN,195.0,94.0,101.0,128.000000,2+,2+,73.0,76.0,0.27,1.0,1.0,0.0,1.0,NaN,151.0,81.0,70.0,104.0,NEG,2+,98.0,54.0,0.07,1.0,1,0,1,NaN,156.0,82,NaN,NEG,96,53,0.01,NaN,44810,1,0,0,1,144,72,72.0,96.0,120.0,97,52,TRACE,NEG,0,NaN,NO,72,NaN
25,2015,6824,39,FEMALE,INDIAN,32,36,1,1.0,1,0,0.0,2+,NEG,1+,1+,81.0,1.5,36.000000,1,0,0,0,0,0,0,1.57,0.27,5.81,382.0,73.0,33,5.17,11.5,416,10.10,3.44,2.08,1.700000,144.0,64.0,80.0,91.0,1.370,2+,64,113,NaN,0,0,0,0,NaN,149.0,103.0,46.0,118.000000,2+,3+,68.0,105.0,0.22,0.0,0.0,0.0,0.0,NaN,156.0,88.0,68.0,111.0,3+,TRACE,77.0,90.0,0.13,1.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,0,0,0,133,82,51.0,99.0,126.0,81,84,2+,3+,0.08,NaN,NO,24,NaN
26,2015,13019,28,FEMALE,MELAYU,21,1,1,0.0,0,0,0.0,2+,NEG,1+,1+,81.2,1.69,28.430000,1,1,0,0,0,0,0,1.41,0.44,3.20,407.0,71.0,35,4.59,13.5,275,10.20,5.84,2.74,2.100000,99.0,73.0,26.0,82.0,2.710,2+,63,123,0.14,1,0,0,0,NaN,130.0,69.0,61.0,89.000000,3+,3+,67.0,129.0,0.24,1.0,0.0,0.0,0.0,NaN,121.0,64.0,57.0,83.0,2+,3+,64.0,120.0,0.27,1.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,1,0,0,0,124,80,44.0,95.0,121.0,58,126,NEG,NEG,0.32,NaN,NO,36,NaN
27,2016,7569,42,FEMALE,OTHERS,36,36,1,0.0,1,1,0.0,2+,NEG,NEG,NEG,76.0,1.51,33.330000,1,1,0,0,0,0,0,1.68,0.43,3.91,423.0,74.0,31,5.64,11.9,305,9.80,6.25,2.66,2.300000,115.0,83.0,32.0,94.0,2.060,2+,118,53,0.57,1,0,0,0,NaN,128.0,89.0,39.0,102.000000,4+,1+,113.0,56.0,0.33,1.0,0.0,0.0,0.0,NaN,121.0,79.0,42.0,93.0,1+,TRACE,113.0,55.0,0.14,1.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,1,0,0,0,149,98,51.0,115.0,148.0,132,45,NEG,2+,0.06,NaN,NO,48,NaN
28,2016,5100,44,MALE,OTHERS,38,24,1,0.0,1,1,0.0,2+,1+,NEG,2+,87.0,1.73,29.070000,1,1,0,0,0,0,0,NaN,NaN,NaN,764.0,69.0,33,6.50,13.0,247,6.70,4.57,2.58,1.800000,122.0,83.0,39.0,96.0,NaN,2+,261,27,0.52,1,0,0,0,NaN,167.0,111.0,56.0,130.000000,2+,2+,276.0,25.0,0.26,1.0,0.0,0.0,0.0,NaN,137.0,73.0,64.0,94.0,2+,2+,284.0,24.0,0.28,1.0,0,0,0,NaN,138.0,85,NaN,TRACE,270,25,0.09,NaN,6/16/2022,1,0,0,0,132,90,42.0,104.0,134.0,274,24,TRACE,1+,0.2,NaN,NO,72,NaN
29,2016,1976,43,FEMALE,MELAYU,36,36,1,0.0,1,1,1.0,2+,NEG,NEG,TRACE,113.8,1.64,42.310000,1,1,1,0,0,0,0,NaN,NaN,NaN,457.0,72.0,33,NaN,12.9,244,10.40,5.10,4.16,1.200000,146.0,82.0,64.0,103.0,NaN,TRACE,72,96,0.62,1,0,0,0,NaN,169.0,105.0,64.0,126.000000,4+,NEG,78.0,87.0,0.20,1.0,0.0,0.0,0.0,NaN,194.0,124.0,70.0,147.0,3+,TRACE,81.0,83.0,0.30,1.0,0,0,0,NaN,185.0,103,NaN,1+,401,12,0.62,NaN,44659,1,0,0,0,133,95,38.0,108.0,139.0,708,6,TRACE,1+,NaN,NaN,ESRD,60,DELETE L
30,2016,5402,35,FEMALE,MELAYU,28,1,1,0.0,1,2,NaN,3+,NEG,NEG,1+,54.3,1.56,22.310000,1,1,1,1,0,0,0,1.18,0.24,4.92,431.0,51.0,21,11.42,10.2,424,6.90,4.26,1.92,2.200000,120.0,83.0,37.0,95.0,NaN,3+,150,42,0.35,1,0,0,0,NaN,147.0,89.0,58.0,108.000000,2+,TRACE,131.0,49.0,0.10,1.0,1.0,0.0,0.0,NaN,133.0,56.0,77.0,82.0,NEG,TRACE,199.0,30.0,0.01,1.0,1,0,0,NaN,132.0,75,NaN,NEG,178,33,0.28,NaN,10/28/2021,1,1,0,0,123,74,49.0,90.0,115.0,505,9,1+,1+,0.09,NaN,ESRD,60,NaN
31,2016,12519,34,FEMALE,MELAYU,28,5,1,1.0,1,0,0.0,3+,NEG,1+,1+,71.4,1.63,26.870000,1,1,0,1,0,0,0,1.42,0.28,5.07,277.0,52.0,23,9.41,12.6,337,9.50,6.07,2.62,2.300000,151.0,114.0,37.0,126.0,NaN,3+,69,106,0.49,1,1,0,0,NaN,163.0,97.0,66.0,119.000000,3+,2+,68.0,108.0,0.41,1.0,1.0,0.0,0.0,NaN,140.0,102.0,38.0,115.0,2+,2+,135.0,47.0,0.15,1.0,1,1,0,NaN,118.0,77,NaN,3+,244,23,0.22,NaN,44873,1,1,0,0,126,87,39.0,100.0,129.0,170,35,2+,3+,0.27,NaN,50PERC,12,"DELETE 5,L"
32,2016,13616,26,FEMALE,OTHERS,20,2,1,0.0,1,1,0.0,3+,1+,2+,1+,58.2,1.6,22.730000,1,1,0,0,0,0,0,1.13,0.18,6.28,349.0,NaN,26,6.42,9.6,320,5.20,2.95,1.49,2.000000,132.0,82.0,50.0,99.0,NaN,3+,74,102,0.35,1,0,0,0,NaN,144.0,84.0,60.0,104.000000,3+,2+,69.0,111.0,0.19,1.0,0.0,0.0,0.0,NaN,110.0,80.0,30.0,90.0,2+,3+,70.0,109.0,0.12,1.0,1,1,0,NaN,107.0,68,NaN,3+,93,68,0.16,NaN,5/19/2022,1,1,0,0,125,84,41.0,98.0,126.0,102,67,3+,NEG,0.15,NaN,NO,72,NaN
33,2017,1009,49,FEMALE,MELAYU,44,82,1,0.0,1,0,0.0,2+,NEG,1+,TRACE,63.0,NaN,NaN,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,71.0,36,5.67,12.5,301,10.40,6.56,2.88,2.300000,132.0,66.0,66.0,88.0,NaN,3+,75,87,0.40,1,1,0,0,NaN,119.0,57.0,62.0,78.000000,4+,3+,74.0,88.0,0.30,1.0,1.0,0.0,0.0,NaN,110.0,58.0,52.0,75.0,NaN,NaN,73.0,89.0,0.21,1.0,1,0,0,NaN,126.0,84,NaN,TRACE,81,77,0.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,60,NaN
34,2017,6691,31,FEMALE,MELAYU,26,12,1,0.0,0,0,0.0,2+,TRACE,1+,2+,61.0,-,NaN,1,1,0,1,0,0,0,1.44,0.35,4.11,251.0,70.0,33,6.41,12.6,293,8.80,5.41,2.55,2.100000,110.0,61.0,49.0,77.0,1.600,NEG,65,115,0.31,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0,69.0,42.0,83.0,1+,NEG,50.0,128.0,0.03,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,12,NaN
35,2017,1696,51,FEMALE,MELAYU,46,2,1,1.0,1,0,1.0,3+,NEG,TRACE,1+,80.0,1.53,34.170000,1,1,1,1,0,0,0,1.71,0.48,3.56,NaN,58.0,27,5.47,10.1,370,11.40,5.72,2.43,2.400000,103.0,69.0,34.0,80.0,NaN,3+,83,76,0.27,1,0,0,0,NaN,158.0,97.0,61.0,117.000000,4+,NEG,92.0,67.0,0.18,1.0,1.0,0.0,0.0,NaN,140.0,80.0,60.0,100.0,2+,1+,128.0,45.0,0.02,1.0,1,1,1,NaN,136.0,82,NaN,NEG,84,73,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,60,NaN
36,2017,2990,55,FEMALE,MELAYU,49,8,1,0.0,1,1,0.0,3+,NEG,TRACE,NEG,79.0,-,NaN,1,1,1,0,0,0,0,NaN,NaN,NaN,460.0,65.0,32,4.74,11.4,349,6.80,3.69,2.25,1.600000,120.0,74.0,46.0,89.0,3.350,3+,195,27,0.21,1,0,0,0,NaN,130.0,89.0,41.0,103.000000,NEEG,TRACE,209.0,25.0,0.05,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,6,NaN
37,2017,4733,30,FEMALE,MELAYU,24,13,1,0.0,1,1,0.0,3+,NEG,1+,1+,75.2,NaN,NaN,1,1,0,0,0,0,0,1.56,0.39,4.00,328.0,NaN,33,7.06,12.6,331,8.50,4.26,2.76,1.500000,112.0,75.0,37.0,87.0,NaN,TRACE,70,107,0.09,1,0,0,0,NaN,115.0,60.0,55.0,78.000000,NEG,NEG,69.0,109.0,0.07,1.0,0.0,0.0,0.0,NaN,119.0,76.0,43.0,90.0,1+,TRACE,75.0,98.0,0.03,1.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,12,NaN
38,2017,13287,38,FEMALE,OTHERS,33,12,1,0.0,1,0,0.0,NaN,NaN,NaN,NaN,67.0,1.64,24.910767,1,0,0,0,0,0,0,1.19,0.33,3.61,310.0,NaN,36,NaN,12.1,250,8.70,5.18,2.64,1.962121,106.0,66.0,40.0,79.0,NaN,TRACE,67,106,0.12,1,0,0,0,NaN,104.0,67.0,37.0,79.000000,TRACE,NEG,68.0,105.0,0.03,1.0,0.0,0.0,0.0,NaN,113.0,60.0,53.0,78.0,TRACE,NEG,68.0,NaN,0.08,1.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NEG,1+,0.09,NaN,NO,25,NaN
39,2018,10737,46,FEMALE,MELAYU,42,36,1,0.0,0,0,0.0,2+,TRACE,TRACE,NEG,58.0,1.53,24.780000,1,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,31,5.59,11.1,371,8.70,3.89,3.99,1.000000,131.0,98.0,33.0,109.0,2.000,2+,86,100,0.20,1,0,0,0,NaN,130.0,80.0,50.0,97.000000,1+,2+,75.0,88.0,0.13,1.0,0.0,0.0,0.0,NaN,118.0,84.0,34.0,95.0,TRACE,1+,77.0,85.0,0.13,1.0,0,0,0,NaN,NaN,-,NaN,-,-,-,--,NaN,44810,1,0,0,0,114,82,32.0,93.0,120.0,94,65,3+,1+,0.14,NaN,NO,48,NaN
40,2017,6644,45,FEMALE,MELAYU,40,NaN,1,0.0,1,1,0.0,2+,TRACE,1+,1+,72.0,1.53,30.760000,1,0,1,0,0,0,0,1.46,0.33,4.42,516.0,NaN,35,7.06,11.7,441,10.20,6.80,2.22,3.100000,129.0,80.0,49.0,96.0,NaN,2+,248,21,0.61,1,0,0,0,NaN,131.0,95.0,36.0,107.000000,4+,2+,609.0,7.0,0.82,1.0,0.0,0.0,0.0,NaN,146.0,99.0,47.0,115.0,1+,NEG,374.0,13.0,0.30,0.0,0,0,0,NaN,196.0,84,NaN,-,975,4,--,NaN,-,-,-,-,-,-,-,NaN,NaN,NaN,-,-,-,-,-,NaN,ESRD,6,"DELETE 1,5"
41,2018,10735,42,FEMALE,MELAYU,38,NaN,1,0.0,0,0,0.0,3+,2+,1+,1+,89.0,1.57,36.110000,1,0,1,0,0,0,0,1.21,0.34,3.56,484.0,NaN,30,5.77,12.2,410,11.30,7.63,2.55,3.000000,180.0,110.0,70.0,133.0,2.340,TRACE,123,50,0.07,1,0,0,0,NaN,172.0,89.0,83.0,117.000000,2+,TRACE,128.0,47.0,0.14,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,1+,NEG,142.0,42.0,0.16,1.0,0,0,0,NaN,NaN,-,NaN,-,-,-,--,NaN,1//08/2022,1,0,0,0,111,75,36.0,87.0,112.0,218,24,1+,2+,0.26,NaN,NO,36,NaN

In [149]:
#SELECTING THE NEEDED COLUMNS FOR THE ANALYSIS
df1 = CKData[['AGE', 'GENDER', 'B_PROTEIN', 'B_ALBUMIN',	'B_CHOLESTEROL',	'B_HEMATOCRIT', 'B_PLATELET',	'WBC',
                             'NEUTRO',	'LYMPHO',	'NLR',	'B_SBP',	'B_DBP',	'B_PP', 'B_MAP',	'HEMATURIA',	'B_creatinine',
                             'B_eGFR',	'B_UPCR',	'B_ACE',	'B_STEROID',	'B_CYTOTOXICS',	'B_AZATHIOPRINE', 'OUTCOME']]

In [150]:
#showing last 10 observations in the data newly created data column called df1
df1.tail(10)

,AGE,GENDER,B_PROTEIN,B_ALBUMIN,B_CHOLESTEROL,B_HEMATOCRIT,B_PLATELET,WBC,NEUTRO,LYMPHO,NLR,B_SBP,B_DBP,B_PP,B_MAP,HEMATURIA,B_creatinine,B_eGFR,B_UPCR,B_ACE,B_STEROID,B_CYTOTOXICS,B_AZATHIOPRINE,OUTCOME
71,24,FEMALE,72.0,35,5.76,11.7,256,12.00,8.59,2.63,3.3,138.0,90.0,48.0,106.0,2+,121,55,0.29,1,0,0,0,NO
72,23,MALE,66.0,36,4.76,15.7,277,8.71,4.40,2.82,1.6,117.0,78.0,39.0,91.0,2+,93,103,0.09,0,1,0,0,NO
73,37,MALE,NaN,28,6.19,14.3,336,15.80,10.83,3.84,2.8,173.0,119.0,54.0,137.0,1+,378,18,0.76,1,0,0,0,ESRD
74,26,MALE,41.0,8,NaN,16.2,269,10.80,7.82,2.18,3.6,131.0,73.0,58.0,92.0,NEG,74,126,0.81,1,1,0,0,NO
75,26,FEMALE,71.0,34,5.76,12.1,295,8.00,5.18,1.70,3.0,125.0,60.0,65.0,82.0,3+,162,39,0.31,0,0,0,0,NO
76,34,MALE,NaN,39,5.08,15.4,262,9.50,5.22,3.52,1.5,144.0,88.0,56.0,107.0,2+,121,70,0.20,0,0,0,0,NO
77,31,FEMALE,54.0,22,9.65,10.9,388,7.00,4.13,2.04,2.0,144.0,107.0,37.0,119.0,2+,207,29,0.94,1,1,0,0,ESRD
78,38,FEMALE,73.0,33,6.12,12.7,273,8.30,4.04,3.32,1.2,138.0,83.0,55.0,101.0,NEG,90,74,0.17,1,0,0,0,NO
79,24,FEMALE,NaN,38,4.28,12.8,399,9.40,6.48,2.17,3.0,129.0,69.0,60.0,89.0,2+,67,115,0.18,1,0,0,0,NO
80,34,MALE,50.0,18,5.71,15.6,410,7.50,4.28,2.35,1.8,134.0,85.0,49.0,101.0,2+,132,65,1.05,1,0,0,0,NO

In [153]:
#checking out the gender column
df1['GENDER'].describe()

count         81
unique         2
top       FEMALE
freq          60
Name: GENDER, dtype: object

In [158]:
#checking out the haematuria column
df1['HEMATURIA'].describe()

count     81
unique     6
top       2+
freq      24
Name: HEMATURIA, dtype: object

In [161]:
#checking out the outcome column
df1['OUTCOME'].describe()

count     81
unique     3
top       NO
freq      60
Name: OUTCOME, dtype: object

In [163]:
#viewing all columns with empty observation
df1[df1.columns[df1.isna().any()]]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]

In [156]:
#Filling out missing values with mean valuee of the column
df1[['B_PROTEIN',	'B_CHOLESTEROL',	'B_SBP',	'B_DBP',	'B_PP',	'B_MAP',	'B_UPCR']] = df1[['B_PROTEIN', 'B_CHOLESTEROL',	'B_SBP',
                                                                                        'B_DBP',	'B_PP',	'B_MAP','B_UPCR']].fillna(df1[['B_PROTEIN', 'B_CHOLESTEROL',	'B_SBP',
                                                                                                                                        'B_DBP', 'B_PP','B_MAP',	'B_UPCR']].mean())

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [157]:
df1.isnull().any()

AGE               False
GENDER            False
B_PROTEIN         False
B_ALBUMIN         False
B_CHOLESTEROL     False
B_HEMATOCRIT      False
B_PLATELET        False
WBC               False
NEUTRO            False
LYMPHO            False
NLR               False
B_SBP             False
B_DBP             False
B_PP              False
B_MAP             False
HEMATURIA         False
B_creatinine      False
B_eGFR            False
B_UPCR            False
B_ACE             False
B_STEROID         False
B_CYTOTOXICS      False
B_AZATHIOPRINE    False
OUTCOME           False
dtype: bool

In [129]:
df1

,AGE,GENDER,B_PROTEIN,B_ALBUMIN,B_CHOLESTEROL,B_HEMATOCRIT,B_PLATELET,WBC,NEUTRO,LYMPHO,NLR,B_SBP,B_DBP,B_PP,B_MAP,HEMATURIA,B_creatinine,B_eGFR,B_UPCR,B_ACE,B_STEROID,B_CYTOTOXICS,B_AZATHIOPRINE,OUTCOME
0,40,FEMALE,71.000000,35,3.780000,12.5,311,11.90,6.33,2.87,2.200000,139.0000,96.0000,43.00,110.00,NEG,121,53,0.110000,1,0,0,0,ESRD
1,38,FEMALE,68.000000,33,6.689219,11.7,413,10.70,7.74,1.91,4.100000,120.0000,81.0000,39.00,94.00,2+,82,86,0.400000,0,0,0,0,50PERC
2,38,FEMALE,63.000000,35,6.689219,12.1,433,13.10,10.90,1.40,7.800000,149.0000,103.0000,46.00,118.00,NEG,74,98,0.260000,1,1,0,0,NO
3,41,FEMALE,73.000000,39,6.970000,13.3,365,15.90,11.90,3.09,3.900000,132.0000,78.0000,54.00,96.00,NEG,59,120,0.140000,0,1,0,0,NO
4,34,MALE,50.000000,20,8.650000,13.2,310,7.30,3.97,2.52,1.600000,135.0000,82.0000,53.00,100.00,NEG,76,124,0.630000,0,0,1,0,NO
5,29,MALE,57.000000,28,7.190000,10.0,404,8.80,4.48,1.34,3.300000,145.0000,84.0000,61.00,104.00,2+,370,20,0.670000,0,0,0,0,ESRD
6,32,FEMALE,76.000000,36,4.670000,12.3,302,8.90,5.49,2.75,2.000000,131.0000,68.0000,63.00,89.00,2+,61,126,0.170000,0,0,0,0,NO
7,51,FEMALE,63.000000,31,6.689219,10.8,155,13.20,8.48,2.98,2.800000,134.0000,84.0000,50.00,101.00,3+,331,15,0.710000,0,0,0,0,ESRD
8,34,FEMALE,65.000000,29,7.720000,11.6,122,8.30,5.15,2.40,2.100000,147.0000,96.0000,51.00,113.00,2+,91,77,0.300000,1,0,0,0,NO
9,43,MALE,68.000000,33,4.580000,12.6,287,18.10,13.90,2.65,5.200000,133.0000,84.0000,49.00,100.00,1+,161,49,0.220000,1,0,0,0,50PERC
10,65,MALE,68.000000,34,6.689219,11.5,196,9.20,6.08,2.02,3.000000,129.0000,91.0000,38.00,104.00,1+,293,21,0.290000,1,0,0,0,ESRD
11,32,FEMALE,65.000000,31,4.950000,11.6,268,7.70,4.19,2.93,1.400000,140.0000,85.0000,55.00,103.00,3+,97,73,0.470000,1,0,0,0,50PERC
12,36,FEMALE,73.000000,34,4.620000,12.0,258,6.90,5.14,2.75,1.900000,120.0000,74.0000,46.00,89.00,2+,64,117,0.230000,1,0,0,0,NO
13,31,MALE,69.000000,42,5.060000,13.8,252,7.00,4.58,2.47,1.900000,128.0000,83.0000,45.00,98.00,2+,216,37,0.260000,1,0,0,0,ESRD
14,45,MALE,67.000000,32,6.689219,10.6,238,5.20,2.81,2.04,1.400000,123.0000,79.0000,44.00,94.00,1+,347,19,0.610000,1,0,0,0,ESRD
15,52,FEMALE,72.000000,31,6.689219,11.4,199,6.70,3.87,2.04,1.900000,127.0000,68.0000,59.00,88.00,2+,295,17,0.310000,1,0,0,0,ESRD
16,27,MALE,57.000000,24,9.230000,13.7,293,7.40,4.07,2.23,1.800000,129.0000,81.0000,48.00,97.00,3+,142,63,0.570000,1,0,0,0,ESRD
17,39,FEMALE,59.000000,23,10.340000,12.1,301,7.50,4.89,3.29,1.500000,102.0000,73.0000,29.00,83.00,3+,56,121,0.560000,0,1,0,0,NO
18,55,FEMALE,43.000000,10,13.390000,13.5,452,6.50,4.65,2.00,2.300000,106.0000,74.0000,32.00,85.00,1+,50,113,0.910000,1,0,0,0,NO
19,38,FEMALE,65.000000,23,5.810000,10.4,248,7.00,4.67,1.50,3.100000,128.0000,95.0000,33.00,106.00,5+,319,17,0.320000,1,0,0,0,NO
20,36,MALE,71.000000,31,7.740000,14.4,269,10.90,7.02,2.56,2.700000,121.0000,57.0000,64.00,78.00,TRACE,253,30,0.310000,0,0,0,0,ESRD
21,49,MALE,48.000000,12,3.730000,11.9,111,11.80,5.06,1.18,4.300000,139.0000,86.0000,53.00,104.00,5+,348,19,0.860000,0,0,0,0,NO
22,41,FEMALE,64.000000,28,6.689219,10.2,317,9.00,8.02,2.19,3.700000,102.0000,73.0000,29.00,83.00,3+,80,86,0.100000,1,0,0,0,NO
23,37,FEMALE,68.000000,33,6.100000,12.0,300,13.20,5.79,2.03,2.900000,203.0000,116.0000,87.00,145.00,2+,109,61,0.280000,1,0,0,0,NO
24,70,FEMALE,60.000000,25,5.640000,10.7,407,9.80,5.64,3.52,1.600000,176.0000,76.0000,100.00,109.00,3+,110,47,0.910000,1,0,0,0,NO
25,39,FEMALE,73.000000,33,5.170000,11.5,416,10.10,3.44,2.08,1.700000,144.0000,64.0000,80.00,91.00,2+,64,113,0.397375,0,0,0,0,NO
26,28,FEMALE,71.000000,35,4.590000,13.5,275,10.20,5.84,2.74,2.100000,99.0000,73.0000,26.00,82.00,2+,63,123,0.140000,1,0,0,0,NO
27,42,FEMALE,74.000000,31,5.640000,11.9,305,9.80,6.25,2.66,2.300000,115.0000,83.0000,32.00,94.00,2+,118,53,0.570000,1,0,0,0,NO
28,44,MALE,69.000000,33,6.500000,13.0,247,6.70,4.57,2.58,1.800000,122.0000,83.0000,39.00,96.00,2+,261,27,0.520000,1,0,0,0,NO
29,43,FEMALE,72.000000,33,6.689219,12.9,244,10.40,5.10,4.16,1.200000,146.0000,82.0000,64.00,103.00,TRACE,72,96,0.620000,1,0,0,0,ESRD
30,35,FEMALE,51.000000,21,11.420000,10.2,424,6.90,4.26,1.92,2.200000,120.0000,83.0000,37.00,95.00,3+,150,42,0.350000,1,0,0,0,ESRD
31,34,FEMALE,52.000000,23,9.410000,12.6,337,9.50,6.07,2.62,2.300000,151.0000,114.0000,37.00,126.00,3+,69,106,0.490000,1,1,0,0,50PERC
32,26,FEMALE,62.639344,26,6.420000,9.6,320,5.20,2.95,1.49,2.000000,132.0000,82.0000,50.00,99.00,3+,74,102,0.350000,1,0,0,0,NO
33,49,FEMALE,71.000000,36,5.670000,12.5,301,10.40,6.56,2.88,2.300000,132.0000,66.0000,66.00,88.00,3+,75,87,0.400000,1,1,0,0,NO
34,31,FEMALE,70.000000,33,6.410000,12.6,293,8.80,5.41,2.55,2.100000,110.0000,61.0000,49.00,77.00,NEG,65,115,0.310000,0,0,0,0,NO
35,51,FEMALE,58.000000,27,5.470000,10.1,370,11.40,5.72,2.43,2.400000,103.0000,69.0000,34.00,80.00,3+,83,76,0.270000,1,0,0,0,NO
36,55,FEMALE,65.000000,32,4.740000,11.4,349,6.80,3.69,2.25,1.600000,120.0000,74.0000,46.00,89.00,3+,195,27,0.210000,1,0,0,0,NO
37,30,FEMALE,62.639344,33,7.060000,12.6,331,8.50,4.26,2.76,1.500000,112.0000,75.0000,37.00,87.00,TRACE,70,107,0.090000,1,0,0,0,NO
38,38,FEMALE,62.639344,36,6.689219,12.1,250,8.70,5.18,2.64,1.962121,106.0000,66.0000,40.00,79.00,TRACE,67,106,0.120000,1,0,0,0,NO
39,46,FEMALE,62.639344,31,5.590000,11.1,371,8.70,3.89,3.99,1.000000,131.0000,98.0000,33.00,109.00,2+,86,100,0.200000,1,0,0,0,NO
40,45,FEMALE,62.639344,35,7.060000,11.7,441,10.20,6.80,2.22,3.100000,129.0000,80.0000,49.00,96.00,2+,248,21,0.610000,1,0,0,0,ESRD
41,42,FEMALE,62.639344,30,5.770000,12.2,410,11.30,7.63,2.55,3.000000,180.0000,110.0000,70.00,133.00,TRACE,123,50,0.070000,1,0,0,0,NO
42,29,FEMALE,62.639344,36,4.600000,12.4,337,8.30,5.20,2.45,2.100000,112.0000,67.0000,45.00,82.00,TRACE,65,116,0.260000,1,0,0,0,NO
43,32,MALE,62.639344,23,11.010000,15.3,196,6.90,5.08,1.41,3.600000,156.0000,81.0000,75.00,106.00,TRACE,93,96,0.530000,1,1,0,0,NO
44,33,FEMALE,62.639344,32,6.689219,10.6,296,8.10,4.79,1.78,2.700000,132.0000,78.0000,54.00,96.00,1+,228,25,0.720000,1,1,0,0,ESRD
45,35,FEMALE,62.639344,23,6.689219,11.6,362,7.90,4.56,2.71,1.700000,110.0000,70.0000,40.00,83.00,1+,70,102,0.710000,1,0,0,0,NO
46,36,FEMALE,63.000000,28,7.570000,9.9,325,5.50,3.01,1.58,1.900000,114.0000,73.0000,41.00,87.00,2+,56,121,0.480000,0,0,0,0,NO
47,38,FEMALE,62.639344,35,6.689219,13.5,381,9.70,5.45,3.24,1.700000,146.0000,107.0000,39.00,120.00,1+,56,120,0.160000,1,0,0,0,NO
48,57,FEMALE,36.000000,36,7.190000,11.5,408,10.50,6.12,2.92,2.100000,138.0000,75.0000,63.00,96.00,NEG,78,78,1.120000,1,0,0,0,NO
49,26,FEMALE,62.639344,20,6.689219,10.6,328,7.20,3.50,2.15,1.600000,98.0000,62.0000,36.00,74.00,3+,53,132,0.380000,0,0,0,0,NO
50,34,MALE,62.639344,42,7.710000,13.4,317,6.70,3.70,2.16,1.700000,126.0000,85.0000,41.00,99.00,1+,194,40,0.080000,0,1,0,0,NO
51,50,FEMALE,62.639344,38,6.330000,11.4,264,4.50,4.14,0.96,4.300000,151.0000,86.0000,65.00,108.00,TRACE,124,47,0.160000,1,0,0,0,NO
52,48,MALE,63.000000,32,5.810000,13.8,291,9.40,6.62,2.10,3.200000,117.0000,68.0000,49.00,84.00,1+,104,77,0.040000,1,0,0,0,NO
53,48,FEMALE,62.639344,42,8.610000,13.2,344,7.70,3.67,3.06,1.200000,142.0000,61.0000,81.00,88.00,1+,64,104,0.080000,0,0,0,0,NO
54,54,FEMALE,83.000000,34,3.410000,9.6,309,7.40,4.42,2.33,1.900000,132.7875,81.9375,50.85,98.85,1+,209,24,0.430000,1,0,0,0,ESRD
55,32,FEMALE,51.000000,6,10.930000,13.1,689,5.80,2.79,2.80,1.000000,102.0000,53.0000,49.00,69.00,NEG,37,136,0.770000,0,1,0,0,NO
56,37,FEMALE,51.000000,33,7.460000,12.2,278,16.70,14.47,1.64,8.800000,161.0000,107.0000,54.00,125.00,NEG,108,79,0.660000,1,1,0,0,NO
57,24,FEMALE,0.000000,40,6.689219,12.1,307,5.10,2.89,1.92,1.500000,163.0000,108.0000,55.00,126.00,2+,57,128,0.260000,1,0,0,0,NO
58,51,FEMALE,72.000000,30,3.600000,13.0,256,7.20,3.71,2.73,1.400000,137.0000,90.0000,47.00,106.00,3+,82,75,0.230000,0,0,1,0,NO
59,23,FEMALE,62.639344,19,6.689219,12.7,371,9.60,6.96,1.83,3.800000,134.0000,80.0000,54.00,98.00,3+,52,131,0.100000,1,0,0,0,NO
60,34,FEMALE,62.639344,30,8.840000,11.3,390,19.20,17.84,0.98,18.200000,115.0000,70.0000,45.00,85.00,2+,172,35,0.330000,1,1,1,0,NO
61,42,FEMALE,77.000000,36,6.689219,13.3,370,8.80,5.64,2.30,2.500000,183.0000,98.0000,85.00,126.00,3+,158,36,0.210000,1,0,0,0,NO
62,43,FEMALE,58.000000,23,7.400000,13.1,289,8.80,5.84,2.31,2.500000,147.0000,99.0000,48.00,115.00,3+,154,37,0.630000,1,1,0,0,ESRD
63,38,FEMALE,64.000000,33,4.690000,13.6,307,22.80,15.55,4.75,3.300000,145.0000,87.0000,58.00,106.00,3+,80,84,0.360000,1,1,0,0,NO
64,21,FEMALE,76.000000,37,4.520000,12.8,322,12.70,9.36,2.21,4.200000,149.0000,101.0000,48.00,117.00,1+,167,39,0.370000,1,1,0,0,NO
65,38,FEMALE,58.000000,34,7.620000,13.2,322,14.60,10.04,3.30,3.000000,127.0000,82.0000,45.00,97.00,NEG,147,40,0.190000,0,1,0,0,NO
66,30,MALE,74.000000,35,5.880000,11.4,307,5.34,2.39,2.01,1.200000,106.0000,70.0000,36.00,82.00,1+,103,87,0.090000,1,0,0,0,NO
67,58,MALE,76.000000,36,3.700000,13.6,299,7.88,4.16,2.13,2.000000,128.0000,77.0000,51.00,94.00,2+,137,52,0.020000,0,0,0,0,NO
68,44,FEMALE,76.000000,34,6.480000,12.1,354,11.24,7.92,2.38,3.300000,150.0000,80.0000,70.00,103.00,1+,62,110,0.140000,1,1,0,0,NO
69,25,FEMALE,48.000000,21,12.260000,11.4,368,17.70,11.91,4.11,2.900000,128.0000,87.0000,41.00,101.00,3+,56,126,0.530000,1,1,0,0,NO
70,25,MALE,39.000000,17,12.090000,13.6,249,7.80,4.29,2.13,2.000000,143.0000,71.0000,72.00,95.00,1+,106,87,1.030000,0,1,0,0,NO
71,24,FEMALE,72.000000,35,5.760000,11.7,256,12.00,8.59,2.63,3.300000,138.0000,90.0000,48.00,106.00,2+,121,55,0.290000,1,0,0,0,NO
72,23,MALE,66.000000,36,4.760000,15.7,277,8.71,4.40,2.82,1.600000,117.0000,78.0000,39.00,91.00,2+,93,103,0.090000,0,1,0,0,NO
73,37,MALE,62.639344,28,6.190000,14.3,336,15.80,10.83,3.84,2.800000,173.0000,119.0000,54.00,137.00,1+,378,18,0.760000,1,0,0,0,ESRD
74,26,MALE,41.000000,8,6.689219,16.2,269,10.80,7.82,2.18,3.600000,131.0000,73.0000,58.00,92.00,NEG,74,126,0.810000,1,1,0,0,NO
75,26,FEMALE,71.000000,34,5.760000,12.1,295,8.00,5.18,1.70,3.000000,125.0000,60.0000,65.00,82.00,3+,162,39,0.310000,0,0,0,0,NO
76,34,MALE,62.639344,39,5.080000,15.4,262,9.50,5.22,3.52,1.500000,144.0000,88.0000,56.00,107.00,2+,121,70,0.200000,0,0,0,0,NO
77,31,FEMALE,54.000000,22,9.650000,10.9,388,7.00,4.13,2.04,2.000000,144.0000,107.0000,37.00,119.00,2+,207,29,0.940000,1,1,0,0,ESRD
78,38,FEMALE,73.000000,33,6.120000,12.7,273,8.30,4.04,3.32,1.200000,138.0000,83.0000,55.00,101.00,NEG,90,74,0.170000,1,0,0,0,NO
79,24,FEMALE,62.639344,38,4.280000,12.8,399,9.40,6.48,2.17,3.000000,129.0000,69.0000,60.00,89.00,2+,67,115,0.180000,1,0,0,0,NO
80,34,MALE,50.000000,18,5.710000,15.6,410,7.50,4.28,2.35,1.800000,134.0000,85.0000,49.00,101.00,2+,132,65,1.050000,1,0,0,0,NO

In [134]:
#finding unique values in my data set
pd.unique(df1['HEMATURIA'].values.ravel()) #array(['NEG', '2+', '3+', '1+', '5+', 'TRACE'], dtype=object)
pd.unique(df1['OUTCOME'].values.ravel()) #array(['ESRD', '50PERC', 'NO'], dtype=object)
pd.unique(df1[['GENDER']].values.ravel())#array(['FEMALE', 'MALE'], dtype=object)

array(['FEMALE', 'MALE'], dtype=object)

In [135]:
df1.dtypes

AGE                 int64
GENDER             object
B_PROTEIN         float64
B_ALBUMIN           int64
B_CHOLESTEROL     float64
B_HEMATOCRIT      float64
B_PLATELET          int64
WBC               float64
NEUTRO            float64
LYMPHO            float64
NLR               float64
B_SBP             float64
B_DBP             float64
B_PP              float64
B_MAP             float64
HEMATURIA          object
B_creatinine        int64
B_eGFR              int64
B_UPCR            float64
B_ACE               int64
B_STEROID           int64
B_CYTOTOXICS        int64
B_AZATHIOPRINE      int64
OUTCOME            object
dtype: object

In [136]:
for col in ["GENDER", "OUTCOME", "HEMATURIA"]:
    df1[col] = df1[col].replace("\s+", " ", regex=True).str.strip()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [137]:
#Changing the hematuria column to dummy variables where Neg = 0, trace = 1, 1+ = 2, 2+ = 3, 3+ = 4, 5+ = 5
df1.loc[df1['HEMATURIA'] == 'NEG', 'HEMATURIA'] = 0
df1.loc[df1['HEMATURIA'] == 'TRACE', 'HEMATURIA'] = 1
df1.loc[df1['HEMATURIA'] == '1+', 'HEMATURIA'] = 2
df1.loc[df1['HEMATURIA'] == '2+', 'HEMATURIA'] = 3
df1.loc[df1['HEMATURIA'] == '3+', 'HEMATURIA'] = 4
df1.loc[df1['HEMATURIA'] == '5+', 'HEMATURIA'] = 5

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [138]:
df1['HEMATURIA'].describe()

count     81
unique     6
top        3
freq      24
Name: HEMATURIA, dtype: int64

In [139]:
#changing the gender column to dummy variables where male =1 and female = 0
df1['GENDER'] = np.where(df1["GENDER"] == 'FEMALE', 0 ,1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [140]:
df1["GENDER"].describe()

count    81.000000
mean      0.259259
std       0.440959
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000
Name: GENDER, dtype: float64

In [141]:
#changing the outcome column to a dummy variable esrd = 2, 50perc = 1, no = 0
df1.loc[df1["OUTCOME"] == "ESRD", "OUTCOME"] = 2
df1.loc[df1["OUTCOME"] == "50PERC", "OUTCOME"] = 1
df1.loc[df1["OUTCOME"] == "NO", "OUTCOME"] = 0

In [143]:
df1['OUTCOME'].describe()

count     81
unique     3
top        0
freq      60
Name: OUTCOME, dtype: int64

In [144]:
df1

,AGE,GENDER,B_PROTEIN,B_ALBUMIN,B_CHOLESTEROL,B_HEMATOCRIT,B_PLATELET,WBC,NEUTRO,LYMPHO,NLR,B_SBP,B_DBP,B_PP,B_MAP,HEMATURIA,B_creatinine,B_eGFR,B_UPCR,B_ACE,B_STEROID,B_CYTOTOXICS,B_AZATHIOPRINE,OUTCOME
0,40,0,71.000000,35,3.780000,12.5,311,11.90,6.33,2.87,2.200000,139.0000,96.0000,43.00,110.00,0,121,53,0.110000,1,0,0,0,2
1,38,0,68.000000,33,6.689219,11.7,413,10.70,7.74,1.91,4.100000,120.0000,81.0000,39.00,94.00,3,82,86,0.400000,0,0,0,0,1
2,38,0,63.000000,35,6.689219,12.1,433,13.10,10.90,1.40,7.800000,149.0000,103.0000,46.00,118.00,0,74,98,0.260000,1,1,0,0,0
3,41,0,73.000000,39,6.970000,13.3,365,15.90,11.90,3.09,3.900000,132.0000,78.0000,54.00,96.00,0,59,120,0.140000,0,1,0,0,0
4,34,1,50.000000,20,8.650000,13.2,310,7.30,3.97,2.52,1.600000,135.0000,82.0000,53.00,100.00,0,76,124,0.630000,0,0,1,0,0
5,29,1,57.000000,28,7.190000,10.0,404,8.80,4.48,1.34,3.300000,145.0000,84.0000,61.00,104.00,3,370,20,0.670000,0,0,0,0,2
6,32,0,76.000000,36,4.670000,12.3,302,8.90,5.49,2.75,2.000000,131.0000,68.0000,63.00,89.00,3,61,126,0.170000,0,0,0,0,0
7,51,0,63.000000,31,6.689219,10.8,155,13.20,8.48,2.98,2.800000,134.0000,84.0000,50.00,101.00,4,331,15,0.710000,0,0,0,0,2
8,34,0,65.000000,29,7.720000,11.6,122,8.30,5.15,2.40,2.100000,147.0000,96.0000,51.00,113.00,3,91,77,0.300000,1,0,0,0,0
9,43,1,68.000000,33,4.580000,12.6,287,18.10,13.90,2.65,5.200000,133.0000,84.0000,49.00,100.00,2,161,49,0.220000,1,0,0,0,1
10,65,1,68.000000,34,6.689219,11.5,196,9.20,6.08,2.02,3.000000,129.0000,91.0000,38.00,104.00,2,293,21,0.290000,1,0,0,0,2
11,32,0,65.000000,31,4.950000,11.6,268,7.70,4.19,2.93,1.400000,140.0000,85.0000,55.00,103.00,4,97,73,0.470000,1,0,0,0,1
12,36,0,73.000000,34,4.620000,12.0,258,6.90,5.14,2.75,1.900000,120.0000,74.0000,46.00,89.00,3,64,117,0.230000,1,0,0,0,0
13,31,1,69.000000,42,5.060000,13.8,252,7.00,4.58,2.47,1.900000,128.0000,83.0000,45.00,98.00,3,216,37,0.260000,1,0,0,0,2
14,45,1,67.000000,32,6.689219,10.6,238,5.20,2.81,2.04,1.400000,123.0000,79.0000,44.00,94.00,2,347,19,0.610000,1,0,0,0,2
15,52,0,72.000000,31,6.689219,11.4,199,6.70,3.87,2.04,1.900000,127.0000,68.0000,59.00,88.00,3,295,17,0.310000,1,0,0,0,2
16,27,1,57.000000,24,9.230000,13.7,293,7.40,4.07,2.23,1.800000,129.0000,81.0000,48.00,97.00,4,142,63,0.570000,1,0,0,0,2
17,39,0,59.000000,23,10.340000,12.1,301,7.50,4.89,3.29,1.500000,102.0000,73.0000,29.00,83.00,4,56,121,0.560000,0,1,0,0,0
18,55,0,43.000000,10,13.390000,13.5,452,6.50,4.65,2.00,2.300000,106.0000,74.0000,32.00,85.00,2,50,113,0.910000,1,0,0,0,0
19,38,0,65.000000,23,5.810000,10.4,248,7.00,4.67,1.50,3.100000,128.0000,95.0000,33.00,106.00,5,319,17,0.320000,1,0,0,0,0
20,36,1,71.000000,31,7.740000,14.4,269,10.90,7.02,2.56,2.700000,121.0000,57.0000,64.00,78.00,1,253,30,0.310000,0,0,0,0,2
21,49,1,48.000000,12,3.730000,11.9,111,11.80,5.06,1.18,4.300000,139.0000,86.0000,53.00,104.00,5,348,19,0.860000,0,0,0,0,0
22,41,0,64.000000,28,6.689219,10.2,317,9.00,8.02,2.19,3.700000,102.0000,73.0000,29.00,83.00,4,80,86,0.100000,1,0,0,0,0
23,37,0,68.000000,33,6.100000,12.0,300,13.20,5.79,2.03,2.900000,203.0000,116.0000,87.00,145.00,3,109,61,0.280000,1,0,0,0,0
24,70,0,60.000000,25,5.640000,10.7,407,9.80,5.64,3.52,1.600000,176.0000,76.0000,100.00,109.00,4,110,47,0.910000,1,0,0,0,0
25,39,0,73.000000,33,5.170000,11.5,416,10.10,3.44,2.08,1.700000,144.0000,64.0000,80.00,91.00,3,64,113,0.397375,0,0,0,0,0
26,28,0,71.000000,35,4.590000,13.5,275,10.20,5.84,2.74,2.100000,99.0000,73.0000,26.00,82.00,3,63,123,0.140000,1,0,0,0,0
27,42,0,74.000000,31,5.640000,11.9,305,9.80,6.25,2.66,2.300000,115.0000,83.0000,32.00,94.00,3,118,53,0.570000,1,0,0,0,0
28,44,1,69.000000,33,6.500000,13.0,247,6.70,4.57,2.58,1.800000,122.0000,83.0000,39.00,96.00,3,261,27,0.520000,1,0,0,0,0
29,43,0,72.000000,33,6.689219,12.9,244,10.40,5.10,4.16,1.200000,146.0000,82.0000,64.00,103.00,1,72,96,0.620000,1,0,0,0,2
30,35,0,51.000000,21,11.420000,10.2,424,6.90,4.26,1.92,2.200000,120.0000,83.0000,37.00,95.00,4,150,42,0.350000,1,0,0,0,2
31,34,0,52.000000,23,9.410000,12.6,337,9.50,6.07,2.62,2.300000,151.0000,114.0000,37.00,126.00,4,69,106,0.490000,1,1,0,0,1
32,26,0,62.639344,26,6.420000,9.6,320,5.20,2.95,1.49,2.000000,132.0000,82.0000,50.00,99.00,4,74,102,0.350000,1,0,0,0,0
33,49,0,71.000000,36,5.670000,12.5,301,10.40,6.56,2.88,2.300000,132.0000,66.0000,66.00,88.00,4,75,87,0.400000,1,1,0,0,0
34,31,0,70.000000,33,6.410000,12.6,293,8.80,5.41,2.55,2.100000,110.0000,61.0000,49.00,77.00,0,65,115,0.310000,0,0,0,0,0
35,51,0,58.000000,27,5.470000,10.1,370,11.40,5.72,2.43,2.400000,103.0000,69.0000,34.00,80.00,4,83,76,0.270000,1,0,0,0,0
36,55,0,65.000000,32,4.740000,11.4,349,6.80,3.69,2.25,1.600000,120.0000,74.0000,46.00,89.00,4,195,27,0.210000,1,0,0,0,0
37,30,0,62.639344,33,7.060000,12.6,331,8.50,4.26,2.76,1.500000,112.0000,75.0000,37.00,87.00,1,70,107,0.090000,1,0,0,0,0
38,38,0,62.639344,36,6.689219,12.1,250,8.70,5.18,2.64,1.962121,106.0000,66.0000,40.00,79.00,1,67,106,0.120000,1,0,0,0,0
39,46,0,62.639344,31,5.590000,11.1,371,8.70,3.89,3.99,1.000000,131.0000,98.0000,33.00,109.00,3,86,100,0.200000,1,0,0,0,0
40,45,0,62.639344,35,7.060000,11.7,441,10.20,6.80,2.22,3.100000,129.0000,80.0000,49.00,96.00,3,248,21,0.610000,1,0,0,0,2
41,42,0,62.639344,30,5.770000,12.2,410,11.30,7.63,2.55,3.000000,180.0000,110.0000,70.00,133.00,1,123,50,0.070000,1,0,0,0,0
42,29,0,62.639344,36,4.600000,12.4,337,8.30,5.20,2.45,2.100000,112.0000,67.0000,45.00,82.00,1,65,116,0.260000,1,0,0,0,0
43,32,1,62.639344,23,11.010000,15.3,196,6.90,5.08,1.41,3.600000,156.0000,81.0000,75.00,106.00,1,93,96,0.530000,1,1,0,0,0
44,33,0,62.639344,32,6.689219,10.6,296,8.10,4.79,1.78,2.700000,132.0000,78.0000,54.00,96.00,2,228,25,0.720000,1,1,0,0,2
45,35,0,62.639344,23,6.689219,11.6,362,7.90,4.56,2.71,1.700000,110.0000,70.0000,40.00,83.00,2,70,102,0.710000,1,0,0,0,0
46,36,0,63.000000,28,7.570000,9.9,325,5.50,3.01,1.58,1.900000,114.0000,73.0000,41.00,87.00,3,56,121,0.480000,0,0,0,0,0
47,38,0,62.639344,35,6.689219,13.5,381,9.70,5.45,3.24,1.700000,146.0000,107.0000,39.00,120.00,2,56,120,0.160000,1,0,0,0,0
48,57,0,36.000000,36,7.190000,11.5,408,10.50,6.12,2.92,2.100000,138.0000,75.0000,63.00,96.00,0,78,78,1.120000,1,0,0,0,0
49,26,0,62.639344,20,6.689219,10.6,328,7.20,3.50,2.15,1.600000,98.0000,62.0000,36.00,74.00,4,53,132,0.380000,0,0,0,0,0
50,34,1,62.639344,42,7.710000,13.4,317,6.70,3.70,2.16,1.700000,126.0000,85.0000,41.00,99.00,2,194,40,0.080000,0,1,0,0,0
51,50,0,62.639344,38,6.330000,11.4,264,4.50,4.14,0.96,4.300000,151.0000,86.0000,65.00,108.00,1,124,47,0.160000,1,0,0,0,0
52,48,1,63.000000,32,5.810000,13.8,291,9.40,6.62,2.10,3.200000,117.0000,68.0000,49.00,84.00,2,104,77,0.040000,1,0,0,0,0
53,48,0,62.639344,42,8.610000,13.2,344,7.70,3.67,3.06,1.200000,142.0000,61.0000,81.00,88.00,2,64,104,0.080000,0,0,0,0,0
54,54,0,83.000000,34,3.410000,9.6,309,7.40,4.42,2.33,1.900000,132.7875,81.9375,50.85,98.85,2,209,24,0.430000,1,0,0,0,2
55,32,0,51.000000,6,10.930000,13.1,689,5.80,2.79,2.80,1.000000,102.0000,53.0000,49.00,69.00,0,37,136,0.770000,0,1,0,0,0
56,37,0,51.000000,33,7.460000,12.2,278,16.70,14.47,1.64,8.800000,161.0000,107.0000,54.00,125.00,0,108,79,0.660000,1,1,0,0,0
57,24,0,0.000000,40,6.689219,12.1,307,5.10,2.89,1.92,1.500000,163.0000,108.0000,55.00,126.00,3,57,128,0.260000,1,0,0,0,0
58,51,0,72.000000,30,3.600000,13.0,256,7.20,3.71,2.73,1.400000,137.0000,90.0000,47.00,106.00,4,82,75,0.230000,0,0,1,0,0
59,23,0,62.639344,19,6.689219,12.7,371,9.60,6.96,1.83,3.800000,134.0000,80.0000,54.00,98.00,4,52,131,0.100000,1,0,0,0,0
60,34,0,62.639344,30,8.840000,11.3,390,19.20,17.84,0.98,18.200000,115.0000,70.0000,45.00,85.00,3,172,35,0.330000,1,1,1,0,0
61,42,0,77.000000,36,6.689219,13.3,370,8.80,5.64,2.30,2.500000,183.0000,98.0000,85.00,126.00,4,158,36,0.210000,1,0,0,0,0
62,43,0,58.000000,23,7.400000,13.1,289,8.80,5.84,2.31,2.500000,147.0000,99.0000,48.00,115.00,4,154,37,0.630000,1,1,0,0,2
63,38,0,64.000000,33,4.690000,13.6,307,22.80,15.55,4.75,3.300000,145.0000,87.0000,58.00,106.00,4,80,84,0.360000,1,1,0,0,0
64,21,0,76.000000,37,4.520000,12.8,322,12.70,9.36,2.21,4.200000,149.0000,101.0000,48.00,117.00,2,167,39,0.370000,1,1,0,0,0
65,38,0,58.000000,34,7.620000,13.2,322,14.60,10.04,3.30,3.000000,127.0000,82.0000,45.00,97.00,0,147,40,0.190000,0,1,0,0,0
66,30,1,74.000000,35,5.880000,11.4,307,5.34,2.39,2.01,1.200000,106.0000,70.0000,36.00,82.00,2,103,87,0.090000,1,0,0,0,0
67,58,1,76.000000,36,3.700000,13.6,299,7.88,4.16,2.13,2.000000,128.0000,77.0000,51.00,94.00,3,137,52,0.020000,0,0,0,0,0
68,44,0,76.000000,34,6.480000,12.1,354,11.24,7.92,2.38,3.300000,150.0000,80.0000,70.00,103.00,2,62,110,0.140000,1,1,0,0,0
69,25,0,48.000000,21,12.260000,11.4,368,17.70,11.91,4.11,2.900000,128.0000,87.0000,41.00,101.00,4,56,126,0.530000,1,1,0,0,0
70,25,1,39.000000,17,12.090000,13.6,249,7.80,4.29,2.13,2.000000,143.0000,71.0000,72.00,95.00,2,106,87,1.030000,0,1,0,0,0
71,24,0,72.000000,35,5.760000,11.7,256,12.00,8.59,2.63,3.300000,138.0000,90.0000,48.00,106.00,3,121,55,0.290000,1,0,0,0,0
72,23,1,66.000000,36,4.760000,15.7,277,8.71,4.40,2.82,1.600000,117.0000,78.0000,39.00,91.00,3,93,103,0.090000,0,1,0,0,0
73,37,1,62.639344,28,6.190000,14.3,336,15.80,10.83,3.84,2.800000,173.0000,119.0000,54.00,137.00,2,378,18,0.760000,1,0,0,0,2
74,26,1,41.000000,8,6.689219,16.2,269,10.80,7.82,2.18,3.600000,131.0000,73.0000,58.00,92.00,0,74,126,0.810000,1,1,0,0,0
75,26,0,71.000000,34,5.760000,12.1,295,8.00,5.18,1.70,3.000000,125.0000,60.0000,65.00,82.00,4,162,39,0.310000,0,0,0,0,0
76,34,1,62.639344,39,5.080000,15.4,262,9.50,5.22,3.52,1.500000,144.0000,88.0000,56.00,107.00,3,121,70,0.200000,0,0,0,0,0
77,31,0,54.000000,22,9.650000,10.9,388,7.00,4.13,2.04,2.000000,144.0000,107.0000,37.00,119.00,3,207,29,0.940000,1,1,0,0,2
78,38,0,73.000000,33,6.120000,12.7,273,8.30,4.04,3.32,1.200000,138.0000,83.0000,55.00,101.00,0,90,74,0.170000,1,0,0,0,0
79,24,0,62.639344,38,4.280000,12.8,399,9.40,6.48,2.17,3.000000,129.0000,69.0000,60.00,89.00,3,67,115,0.180000,1,0,0,0,0
80,34,1,50.000000,18,5.710000,15.6,410,7.50,4.28,2.35,1.800000,134.0000,85.0000,49.00,101.00,3,132,65,1.050000,1,0,0,0,0

In [46]:
df1.describe()

,AGE,GENDER,B_PROTEIN,B_ALBUMIN,B_CHOLESTEROL,B_HEMATOCRIT,B_PLATELET,WBC,NEUTRO,LYMPHO,NLR,B_SBP,B_DBP,B_PP,B_MAP,24HRUPROTEIN,B_creatinine,B_eGFR,B_UPCR,B_ACE,B_STEROID,B_CYTOTOXICS,B_AZATHIOPRINE,OUTCOME
count,81.000000,81.0,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.00000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.0,81.0
mean,38.185185,0.0,62.639344,30.074074,6.689219,12.322222,317.234568,9.551481,6.042346,2.446049,2.716816,132.78750,81.937500,50.850000,98.850000,3.057031,130.925926,74.296296,0.397375,0.716049,0.259259,0.037037,0.0,1.0
std,10.141636,0.0,11.492424,7.575912,2.039109,1.414567,80.846347,3.401446,2.985217,0.711830,2.162902,19.91086,14.150392,14.241752,14.821522,1.742165,86.176821,37.617963,0.269197,0.453723,0.440959,0.190029,0.0,0.0
min,21.000000,0.0,0.000000,6.000000,3.410000,9.600000,111.000000,4.500000,2.390000,0.960000,1.000000,98.00000,53.000000,26.000000,69.000000,0.320000,37.000000,15.000000,0.020000,0.000000,0.000000,0.000000,0.0,1.0
25%,31.000000,0.0,60.000000,26.000000,5.590000,11.400000,269.000000,7.300000,4.190000,2.040000,1.700000,120.00000,73.000000,40.000000,88.000000,2.600000,69.000000,39.000000,0.190000,0.000000,0.000000,0.000000,0.0,1.0
50%,37.000000,0.0,62.639344,33.000000,6.689219,12.200000,307.000000,8.800000,5.180000,2.380000,2.100000,132.00000,81.000000,49.000000,97.000000,3.057031,97.000000,77.000000,0.310000,1.000000,0.000000,0.000000,0.0,1.0
75%,44.000000,0.0,71.000000,35.000000,7.190000,13.200000,368.000000,10.700000,6.620000,2.760000,3.000000,144.00000,87.000000,58.000000,106.000000,3.057031,161.000000,107.000000,0.570000,1.000000,1.000000,0.000000,0.0,1.0
max,70.000000,0.0,83.000000,42.000000,13.390000,16.200000,689.000000,22.800000,17.840000,4.750000,18.200000,203.00000,119.000000,100.000000,145.000000,10.940000,378.000000,136.000000,1.120000,1.000000,1.000000,1.000000,0.0,1.0

In [59]:
df1['GENDER'].describe()

count    81.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
Name: GENDER, dtype: float64